# *-* coding: utf-8 *-*
from PySide6 import QtCore, QtWidgets
from core.Settings import TyrantSettings


class Ui_Preferences(object):
    def setupUi(self, Form, Wdg=None):
        self.Form = Form
        Form.resize(450, 550)
        Form.setMaximumSize(450, 550)
        Form.setMinimumSize(450, 550)
        Form.setObjectName('Form')
        self.Layout = QtWidgets.QVBoxLayout()
        self.HLay = QtWidgets.QHBoxLayout()
        self.btnSave = QtWidgets.QPushButton()
        self.btnSave.setText('Save')
        self.btnCancel = QtWidgets.QPushButton()
        self.btnCancel.setText('Cancel')
        self.HLay.addWidget(self.btnCancel)
        self.HLay.addWidget(self.btnSave)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 371, 381))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabPython = QtWidgets.QWidget()
        self.lblPython = QtWidgets.QLabel(self.tabPython)
        self.lblPython.setGeometry(QtCore.QRect(10, 10, 64, 21))
        self.edtPython = QtWidgets.QLineEdit(self.tabPython)
        self.edtPython.setGeometry(QtCore.QRect(70, 0, 231, 33))
        self.lblPythonSupp = QtWidgets.QLabel(self.tabPython)
        self.lblPythonSupp.setGeometry(QtCore.QRect(50, 40, 251, 21))
        self.lblSqlMap = QtWidgets.QLabel(self.tabPython)
        self.lblSqlMap.setGeometry(QtCore.QRect(10, 70, 64, 21))
        self.edtSqlMap = QtWidgets.QLineEdit(self.tabPython)
        self.edtSqlMap.setGeometry(QtCore.QRect(70, 60, 231, 33))
        self.lblSqlMapSupp = QtWidgets.QLabel(self.tabPython)
        self.lblSqlMapSupp.setGeometry(QtCore.QRect(50, 100, 251, 21))
        self.tabWidget.addTab(self.tabPython, "")
        self.tab_2 = QtWidgets.QWidget()
        self.gbxProxy = QtWidgets.QGroupBox(self.tab_2)
        self.gbxProxy.setGeometry(QtCore.QRect(0, 0, 331, 381))
        self.edtIpProxy = QtWidgets.QLineEdit(self.gbxProxy)
        self.edtIpProxy.setGeometry(QtCore.QRect(50, 90, 231, 33))
        self.edtPortProxy = QtWidgets.QLineEdit(self.gbxProxy)
        self.edtPortProxy.setGeometry(QtCore.QRect(50, 130, 101, 33))
        self.cbxTorType = QtWidgets.QComboBox(self.gbxProxy)
        self.cbxTorType.setGeometry(QtCore.QRect(160, 130, 100, 33))
        self.cbxTorType.addItems(['HTTP', 'SOCKS4', 'SOCKS5'])
        self.lblPort = QtWidgets.QLabel(self.gbxProxy)
        self.lblPort.setGeometry(QtCore.QRect(10, 140, 64, 21))
        self.lblIP = QtWidgets.QLabel(self.gbxProxy)
        self.lblIP.setGeometry(QtCore.QRect(10, 100, 81, 21))
        self.rbtnProxy = QtWidgets.QRadioButton(self.gbxProxy)
        self.rbtnProxy.setGeometry(QtCore.QRect(10, 30, 200, 26))
        self.rbtnProxy.setText("Don't use proxy")
        self.rbtnHTTP = QtWidgets.QRadioButton(self.gbxProxy)
        self.rbtnHTTP.setGeometry(QtCore.QRect(10, 60, 109, 26))
        self.rbtnHTTP.setChecked(True)
        self.rbtnHTTP.setObjectName("radioButton")
        self.rbtnSocks = QtWidgets.QRadioButton(self.gbxProxy)
        self.rbtnSocks.setGeometry(QtCore.QRect(150, 60, 109, 26))
        self.rbtnSocks.setObjectName("radioButton_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.Layout.addWidget(self.tabWidget)
        Form.setLayout(self.Layout)
        self.Layout.addLayout(self.HLay)
        self.Settings = TyrantSettings(self)
        self.btnSave.clicked.connect(self.Save)
        self.btnCancel.clicked.connect(Form.close)
        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.Settings.Populate_Prefs()
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.rbtnProxy.toggled.connect(self.ProxyInfo)
        self.rbtnHTTP.toggled.connect(self.ProxyInfo)
        self.rbtnSocks.toggled.connect(self.ProxyInfo)

    def Save(self):
        self.Settings.Save_Prefs()
        self.Form.close()

    def ProxyInfo(self):
        if self.rbtnProxy.isChecked():
            self.lblIP.hide()
            self.lblPort.hide()
            self.edtIpProxy.hide()
            self.edtPortProxy.hide()
            self.cbxTorType.hide()
        else:
            self.lblIP.show()
            self.lblPort.show()
            self.edtIpProxy.show()
            self.edtPortProxy.show()
            self.cbxTorType.hide()
            self.edtIpProxy.setEnabled(True)
        if self.rbtnSocks.isChecked():
            self.edtIpProxy.setText('127.0.0.1')
            self.edtIpProxy.setEnabled(False)
            self.cbxTorType.show()

    def retranslateUi(self, Form):
        Form.setWindowTitle("Preferences")
        self.lblPython.setText("Python:")
        self.lblPythonSupp.setText("Tyrant support Python 3.10 or higher")
        self.lblSqlMap.setText("SQLMap:")
        self.lblSqlMapSupp.setText("Path to sqlmap.py file or directory containing it\n(e.g., /home/user/.sec/sqlmap/sqlmap.py or /home/user/.sec/sqlmap)")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPython), "Python")
        self.gbxProxy.setTitle("Web Proxy")
        self.lblPort.setText("Port:")
        self.lblIP.setText("IP:")
        self.rbtnHTTP.setText("HTTP Proxy")
        self.rbtnSocks.setText("Tor Proxy")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), "Proxy")